name: GmailApi.Client pack & publish

on: 
  pull_request:
    types: [closed]
    branches:
      - master
    paths:
      - 'GoogleApi/src/GmailApi.Client/**'

jobs:
  pack_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup .NET
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/coosmiin/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
      - name: pack NuGet
        run: |  
          cd GoogleApi/src/GmailApi.Client
          dotnet pack -c Release -o out  
      - name: push Nuget
        run: dotnet nuget push ./GoogleApi/src/GmailApi.Client/out/*.nupkg --skip-duplicate --no-symbols true