# name: GoogleApi.Authorization build

# on: 
#   pull_request:
#     branches:
#       - master
#     paths:
#       - 'GoogleApi/src/GoogleApi.Authorization/**'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: setup .NET
#         uses: actions/setup-dotnet@v1
#       - name: dotnet restore
#         run: dotnet restore GoogleApi/src/GoogleApi.Authorization/GoogleApi.Authorization.csproj
#       - name: build
#         run: dotnet build GoogleApi/src/GoogleApi.Authorization/GoogleApi.Authorization.csproj --configuration Release --no-restore
